from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("dashboard/", views.dashboard_page, name="dashboard"),
    path("admin/", views.admin_page, name="admin"),
    path("api/admin/trends", views.admin_trends, name="admin_trends"),
    path("api/dashboard", views.api_dashboard, name="api_dashboard"),
    path("api/presence", views.presence_ping, name="presence_ping"),
    path("api/presence/list", views.presence_list, name="presence_list"),
    path("api/auth", views.api_auth, name="api_auth"),
    path("api/seller/finance_check", views.finance_check_submit, name="finance_check_submit"),
    path("api/seller/update_note", views.update_lead_note, name="update_lead_note"),
    path("api/seller/scan_doc", views.scan_doc, name="scan_doc"),
    path("api/seller/loan_submit", views.loan_submit, name="loan_submit"),
    path("api/insights/seller", views.insights_seller, name="insights_seller"),
    path("api/insights/forecast", views.insights_forecast, name="insights_forecast"),
    path("u/<str:token>/", views.magic_link, name="magic_link"),
    path("s/<str:token>/", views.seller_dashboard, name="seller_dashboard"),
    path("me/", views.me_dashboard, name="me_dashboard"),
    path("login/", views.login_view, name="login"),
    path("auth/line/start", views.line_login_start, name="line_login_start"),
    path("auth/line/callback", views.line_login_callback, name="line_login_callback"),
    path("logout/", views.logout_view, name="logout"),
    path("api/admin/send_line", views.admin_send_line, name="admin_send_line"),
    path("api/admin/send_followup", views.admin_send_followup, name="admin_send_followup"),
    path("api/admin/seller_config", views.admin_seller_config, name="admin_seller_config"),
    path("api/admin/admin_config", views.admin_admin_config, name="admin_admin_config"),
    path("api/admin/tele_config", views.admin_tele_config, name="admin_tele_config"),
    path("api/admin/onhand_config", views.admin_onhand_config, name="admin_onhand_config"),
    path("api/admin/seller_flags", views.admin_seller_flags, name="admin_seller_flags"),
    path("api/admin/schedule_config", views.admin_schedule_config, name="admin_schedule_config"),
    path("api/admin/diagnostics", views.admin_diagnostics, name="admin_diagnostics"),
    path("api/admin/sheets_status", views.admin_sheets_status, name="admin_sheets_status"),
    path("api/admin/sheet_config", views.admin_sheet_config, name="admin_sheet_config"),
    path("api/admin/list_drive_sheets", views.admin_list_drive_sheets, name="admin_list_drive_sheets"),
    path("api/admin/list_tabs", views.admin_list_tabs, name="admin_list_tabs"),
    path("api/admin/system_health", views.admin_system_health, name="admin_system_health"),
    path("api/admin/refresh_data", views.admin_refresh_data, name="admin_refresh_data"),
    path("api/admin/report_config", views.admin_report_config, name="admin_report_config"),
    path("api/admin/report_test", views.admin_report_test, name="admin_report_test"),
    path("api/admin/line_group_name", views.admin_line_group_name, name="admin_line_group_name"),
    path("api/admin/update_release_date", views.update_release_date, name="update_release_date"),
    path("api/admin/export_leadscore", views.admin_export_leadscore, name="admin_export_leadscore"),
    path("api/cron/sync", views.cron_sync, name="cron_sync"),
    path("api/cron/send_line", views.cron_send_line, name="cron_send_line"),
    path("api/cron/tick", views.cron_tick, name="cron_tick"),
]
