# Generated by Django 5.0.6 on 2026-07-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่')),
                ('seller', models.CharField(max_length=40, verbose_name='เซลล์')),
                ('team', models.CharField(blank=True, max_length=20, verbose_name='ทีม')),
                ('follow_total', models.IntegerField(default=0, verbose_name='ต้องตาม')),
                ('stuck_deals', models.IntegerField(default=0, verbose_name='ดีลค้าง')),
                ('not_called', models.IntegerField(default=0, verbose_name='ยังไม่โทร')),
                ('no_status', models.IntegerField(default=0, verbose_name='ไม่มีสถานะ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dash_followup_log',
                'ordering': ['-date', 'seller'],
                'indexes': [models.Index(fields=['-date'], name='dash_follow_date_529838_idx')],
                'unique_together': {('date', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='SellerWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='จันทร์ของสัปดาห์')),
                ('seller', models.CharField(max_length=40, verbose_name='เซลล์')),
                ('team', models.CharField(blank=True, max_length=20, verbose_name='ทีม')),
                ('lead', models.IntegerField(default=0, verbose_name='Lead (ไม่รวม RJ)')),
                ('rj', models.IntegerField(default=0, verbose_name='RJ')),
                ('booking', models.IntegerField(default=0, verbose_name='จอง')),
                ('done', models.IntegerField(default=0, verbose_name='ปล่อย')),
                ('deal_value', models.BigIntegerField(default=0, verbose_name='฿ ปล่อย')),
                ('live', models.IntegerField(default=0, verbose_name='ไลฟ์')),
                ('clip', models.IntegerField(default=0, verbose_name='คลิป')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dash_seller_weekly',
                'ordering': ['-week_start', 'seller'],
                'indexes': [models.Index(fields=['-week_start'], name='dash_seller_week_st_16b5c0_idx')],
                'unique_together': {('week_start', 'seller')},
            },
        ),
    ]
