# Generated by Django 5.0.6 on 2026-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_followuplog_sellerweekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuplog',
            name='nags',
            field=models.IntegerField(default=0, verbose_name='โดนทวง (ครั้ง/วัน)'),
        ),
    ]
