# Generated by Django 5.0.6 on 2026-07-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_followuplog_nags'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuplog',
            name='nag_call',
            field=models.IntegerField(default=0, verbose_name='โดนทวง-โทร'),
        ),
        migrations.AddField(
            model_name='followuplog',
            name='nag_deal',
            field=models.IntegerField(default=0, verbose_name='โดนทวง-ดีล'),
        ),
        migrations.AddField(
            model_name='followuplog',
            name='nag_status',
            field=models.IntegerField(default=0, verbose_name='โดนทวง-สถานะ'),
        ),
    ]
