# Generated by Django 5.0.14 on 2026-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_followuplog_nag_call_followuplog_nag_deal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('kind', models.CharField(db_index=True, max_length=24, verbose_name='ประเภท')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='เรื่อง')),
                ('target', models.CharField(blank=True, max_length=64, verbose_name='ปลายทาง')),
                ('ok', models.BooleanField(db_index=True, default=True, verbose_name='สำเร็จ')),
                ('ms', models.IntegerField(default=0, verbose_name='ใช้เวลา (มิลลิวินาที)')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'ล็อกเหตุการณ์ระบบ',
                'verbose_name_plural': 'ล็อกเหตุการณ์ระบบ',
                'db_table': 'dash_event_log',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['kind', '-at'], name='dash_event__kind_c36253_idx')],
            },
        ),
    ]
