# Generated by Django 6.0.2 on 2026-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='เวลาที่รับเข้า')),
                ('date_th', models.CharField(blank=True, max_length=20, verbose_name='วันที่ (ตามที่พิมพ์)')),
                ('seq', models.CharField(blank=True, max_length=20, verbose_name='คันที่')),
                ('car_model', models.CharField(blank=True, max_length=200, verbose_name='รุ่นรถ')),
                ('car_dropdown', models.CharField(blank=True, max_length=60, verbose_name='รถตามสูตร')),
                ('car_category', models.CharField(blank=True, max_length=60, verbose_name='ประเภทรถ')),
                ('plate', models.CharField(blank=True, max_length=40, verbose_name='ป้ายทะเบียน')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์ติดต่อ')),
                ('seller_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อผู้ขาย')),
                ('profile', models.TextField(blank=True, verbose_name='โปรไฟล์ลูกค้า')),
                ('ads', models.CharField(blank=True, max_length=80, verbose_name='Ads')),
                ('channel', models.CharField(blank=True, max_length=60, verbose_name='ช่องทาง')),
                ('sell_type', models.CharField(blank=True, max_length=30, verbose_name='ขาย/เทิร์น')),
                ('online_offline', models.CharField(blank=True, max_length=20, verbose_name='ออนไลน์/ออฟไลน์')),
                ('case_type', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='เคส')),
                ('purchaser', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='จัดซื้อ')),
                ('sender', models.CharField(blank=True, max_length=60, verbose_name='ผู้ส่ง')),
                ('decision', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='รับซื้อ/ไม่รับซื้อ')),
                ('comment', models.TextField(blank=True, verbose_name='คอมเมนท์จัดซื้อ')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล')),
                ('group_id', models.CharField(blank=True, max_length=64, verbose_name='กลุ่ม LINE')),
                ('group_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อกลุ่ม')),
                ('message_id', models.CharField(blank=True, max_length=64, verbose_name='message id')),
                ('raw_text', models.TextField(blank=True, verbose_name='ข้อความต้นฉบับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='แก้ล่าสุด')),
            ],
            options={
                'verbose_name': 'เคสรับซื้อ/เทิร์นรถ',
                'verbose_name_plural': 'เคสรับซื้อ/เทิร์นรถ',
                'db_table': 'dash_purchase_case',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at', 'decision'], name='dash_purcha_receive_3eac2b_idx'), models.Index(fields=['purchaser', 'decision'], name='dash_purcha_purchas_43d93f_idx')],
            },
        ),
    ]
