# Generated by Django 6.0.2 on 2026-09-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_purchasecase'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchasecase',
            name='dash_purcha_receive_3eac2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasecase',
            name='dash_purcha_purchas_43d93f_idx',
        ),
        migrations.DeleteModel(
            name='PurchaseCase',
        ),
    ]
