# Generated by Django 6.0.2 on 2026-09-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_purchasecase_dash_purcha_receive_3eac2b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ดึงเมื่อ')),
                ('kind', models.CharField(db_index=True, max_length=16, verbose_name='ชนิด')),
                ('ref_id', models.CharField(blank=True, max_length=40, verbose_name='ของใคร')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='คำตอบดิบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลดิบจาก Meta',
                'verbose_name_plural': 'ข้อมูลดิบจาก Meta',
                'db_table': 'dash_meta_raw',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaAdDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่')),
                ('account_id', models.CharField(db_index=True, max_length=32, verbose_name='บัญชีโฆษณา')),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='แคมเปญ')),
                ('campaign_name', models.CharField(blank=True, max_length=300, verbose_name='ชื่อแคมเปญ')),
                ('adset_id', models.CharField(blank=True, max_length=32, verbose_name='ชุดโฆษณา')),
                ('adset_name', models.CharField(blank=True, max_length=300, verbose_name='ชื่อชุดโฆษณา')),
                ('ad_id', models.CharField(db_index=True, max_length=32, verbose_name='โฆษณา')),
                ('ad_name', models.CharField(blank=True, max_length=300, verbose_name='ชื่อโฆษณา')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ใช้เงิน (บาท)')),
                ('impressions', models.IntegerField(default=0, verbose_name='แสดงผล')),
                ('reach', models.IntegerField(default=0, verbose_name='เข้าถึง (คน)')),
                ('clicks', models.IntegerField(default=0, verbose_name='คลิก')),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='actions ดิบ')),
                ('cost_per_action', models.JSONField(blank=True, default=list, verbose_name='ต้นทุนต่อ action ดิบ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ดึงล่าสุด')),
            ],
            options={
                'verbose_name': 'ผลโฆษณา Facebook (รายวัน)',
                'verbose_name_plural': 'ผลโฆษณา Facebook (รายวัน)',
                'db_table': 'dash_meta_ad_daily',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'ad_id'), name='uniq_meta_ad_day')],
            },
        ),
        migrations.CreateModel(
            name='MetaPostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, verbose_name='ดึงเมื่อ')),
                ('snap_date', models.DateField(db_index=True, verbose_name='ยอดสะสม ณ สิ้นวัน')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('page_id', models.CharField(db_index=True, max_length=32, verbose_name='เพจ')),
                ('post_id', models.CharField(db_index=True, max_length=64, verbose_name='โพสต์')),
                ('post_type', models.CharField(blank=True, max_length=32, verbose_name='ชนิด')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='โพสต์เมื่อ')),
                ('permalink', models.URLField(blank=True, max_length=300, verbose_name='ลิงก์')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='ข้อความ (ตัดสั้น)')),
                ('reactions', models.IntegerField(default=0, verbose_name='รีแอ็กรวม')),
                ('reactions_by_type', models.JSONField(blank=True, default=dict, verbose_name='รีแอ็กแยกชนิด')),
                ('comments', models.IntegerField(default=0, verbose_name='คอมเมนต์')),
                ('shares', models.IntegerField(default=0, verbose_name='แชร์')),
                ('clicks', models.IntegerField(default=0, verbose_name='คลิก')),
                ('video_views', models.IntegerField(default=0, verbose_name='วิว (3 วิ+)')),
                ('video_views_organic', models.IntegerField(default=0, verbose_name='วิวออร์แกนิก')),
                ('video_views_paid', models.IntegerField(default=0, verbose_name='วิวจากโฆษณา')),
                ('video_avg_watch_ms', models.IntegerField(default=0, verbose_name='ดูเฉลี่ย (มิลลิวินาที)')),
                ('video_complete_30s', models.IntegerField(default=0, verbose_name='ดูครบ 30 วิ')),
                ('video_view_time_ms', models.BigIntegerField(default=0, verbose_name='เวลาดูรวม (มิลลิวินาที)')),
            ],
            options={
                'verbose_name': 'ยอดโพสต์ Facebook (รายวัน)',
                'verbose_name_plural': 'ยอดโพสต์ Facebook (รายวัน)',
                'db_table': 'dash_meta_post_snapshot',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['post_id', 'snap_date'], name='dash_meta_p_post_id_6d2ecb_idx'), models.Index(fields=['trigger', 'snap_date'], name='dash_meta_p_trigger_801ed4_idx')],
            },
        ),
    ]
