# Generated by Django 6.0.2 on 2026-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_meta_snapshot_ads_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ได้รับเมื่อ')),
                ('event', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ชนิด event')),
                ('client_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='แอป TikTok (client_key)')),
                ('user_openid', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ผู้ใช้ (open_id)')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='TikTok สร้างเมื่อ')),
                ('signature_ok', models.BooleanField(blank=True, null=True, verbose_name='ลายเซ็นถูกต้อง')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content (แกะจาก string แล้ว)')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='body ดิบทั้งก้อน')),
                ('body_hash', models.CharField(max_length=64, unique=True, verbose_name='ลายนิ้วมือ body (กันซ้ำ)')),
            ],
            options={
                'verbose_name': 'event จาก TikTok (webhook)',
                'verbose_name_plural': 'event จาก TikTok (webhook)',
                'db_table': 'dash_tiktok_event',
                'ordering': ['-received_at'],
            },
        ),
    ]
