# Generated by Django 6.0.2 on 2026-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_tiktok_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=120, unique=True, verbose_name='open_id (id ช่องต่อแอป)')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='ชื่อที่เราตั้ง (ตอนสร้างลิงก์)')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อช่อง')),
                ('username', models.CharField(blank=True, max_length=120, verbose_name='@ชื่อผู้ใช้')),
                ('scope', models.CharField(blank=True, max_length=300, verbose_name='สิทธิ์ที่ได้')),
                ('profile', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลช่องจาก TikTok (ไม่มีรูป)')),
                ('access_token', models.TextField(blank=True, verbose_name='access token (เข้ารหัส)')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='access token หมดอายุ')),
                ('refresh_token', models.TextField(blank=True, verbose_name='refresh token (เข้ารหัส)')),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='refresh token หมดอายุ')),
                ('status', models.CharField(choices=[('active', 'ใช้งานได้'), ('error', 'ต่ออายุไม่สำเร็จ'), ('revoked', 'เจ้าของยกเลิกสิทธิ์')], db_index=True, default='active', max_length=10, verbose_name='สถานะ')),
                ('last_error', models.CharField(blank=True, max_length=300, verbose_name='ผิดพลาดล่าสุด')),
                ('connected_by', models.CharField(blank=True, max_length=80, verbose_name='ใครสร้างลิงก์')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='เชื่อมเมื่อ')),
                ('refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='ต่ออายุล่าสุด')),
            ],
            options={
                'verbose_name': 'ช่อง TikTok ที่เชื่อมแล้ว',
                'verbose_name_plural': 'ช่อง TikTok ที่เชื่อมแล้ว',
                'db_table': 'dash_tiktok_account',
                'ordering': ['label', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TikTokRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ดึงเมื่อ')),
                ('kind', models.CharField(db_index=True, max_length=16, verbose_name='ชนิด')),
                ('open_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ช่อง (open_id)')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='คำตอบดิบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลดิบจาก TikTok',
                'verbose_name_plural': 'ข้อมูลดิบจาก TikTok',
                'db_table': 'dash_tiktok_raw',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, verbose_name='ดึงเมื่อ')),
                ('snap_date', models.DateField(db_index=True, verbose_name='ยอด ณ สิ้นวัน')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('open_id', models.CharField(db_index=True, max_length=120, verbose_name='ช่อง (open_id)')),
                ('follower_count', models.BigIntegerField(blank=True, null=True, verbose_name='ผู้ติดตาม')),
                ('following_count', models.BigIntegerField(blank=True, null=True, verbose_name='กำลังติดตาม')),
                ('likes_count', models.BigIntegerField(blank=True, null=True, verbose_name='ไลก์รวมทั้งช่อง')),
                ('video_count', models.IntegerField(blank=True, null=True, verbose_name='จำนวนคลิป')),
            ],
            options={
                'verbose_name': 'ยอดช่อง TikTok (รายวัน)',
                'verbose_name_plural': 'ยอดช่อง TikTok (รายวัน)',
                'db_table': 'dash_tiktok_account_snapshot',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['open_id', 'trigger', 'snap_date'], name='dash_tiktok_open_id_f8ab61_idx')],
            },
        ),
        migrations.CreateModel(
            name='TikTokVideoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, verbose_name='ดึงเมื่อ')),
                ('snap_date', models.DateField(db_index=True, verbose_name='ยอดสะสม ณ สิ้นวัน')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('open_id', models.CharField(db_index=True, max_length=120, verbose_name='ช่อง (open_id)')),
                ('video_id', models.CharField(db_index=True, max_length=64, verbose_name='คลิป')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='โพสต์เมื่อ')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='ชื่อ/คำบรรยาย (ตัดสั้น)')),
                ('share_url', models.URLField(blank=True, max_length=300, verbose_name='ลิงก์คลิป')),
                ('duration', models.IntegerField(default=0, verbose_name='ยาว (วินาที)')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='วิว')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='ไลก์')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='คอมเมนต์')),
                ('share_count', models.BigIntegerField(default=0, verbose_name='แชร์')),
            ],
            options={
                'verbose_name': 'ยอดคลิป TikTok (รายวัน)',
                'verbose_name_plural': 'ยอดคลิป TikTok (รายวัน)',
                'db_table': 'dash_tiktok_video_snapshot',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['video_id', 'snap_date'], name='dash_tiktok_video_i_ea4ac2_idx'), models.Index(fields=['open_id', 'trigger', 'snap_date'], name='dash_tiktok_open_id_4e579a_idx')],
            },
        ),
    ]
