# Generated by Django 6.0.2 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_tiktok_accounts_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, max_length=32, verbose_name='เพจ')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่')),
                ('video_views', models.BigIntegerField(default=0, verbose_name='วิววิดีโอ (ทั้งเพจ)')),
                ('engagements', models.BigIntegerField(default=0, verbose_name='การมีส่วนร่วมกับโพสต์')),
                ('page_views', models.BigIntegerField(default=0, verbose_name='คนเปิดดูเพจ')),
                ('follows', models.BigIntegerField(default=0, verbose_name='ผู้ติดตามใหม่')),
                ('likes', models.BigIntegerField(default=0, verbose_name='กดถูกใจโพสต์')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ดึงล่าสุด')),
            ],
            options={
                'verbose_name': 'ยอดเพจ Facebook (รายวัน)',
                'verbose_name_plural': 'ยอดเพจ Facebook (รายวัน)',
                'db_table': 'dash_meta_page_daily',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('page_id', 'date'), name='uniq_meta_page_day')],
            },
        ),
    ]
