# Generated by Django 6.0.2 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_meta_page_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่ของยอด')),
                ('platform', models.CharField(db_index=True, max_length=8, verbose_name='แพลตฟอร์ม')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='โพสต์/คลิป')),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='เพจ/ช่อง')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ข้อความ/ชื่อคลิป (ย่อ)')),
                ('views', models.BigIntegerField(default=0, verbose_name='วิว (วันนั้น)')),
                ('likes', models.BigIntegerField(default=0, verbose_name='ไลก์ (วันนั้น)')),
                ('comments', models.BigIntegerField(default=0, verbose_name='คอมเมนต์ (วันนั้น)')),
                ('shares', models.BigIntegerField(default=0, verbose_name='แชร์ (วันนั้น)')),
                ('cum_views', models.BigIntegerField(default=0, verbose_name='วิวสะสม')),
                ('cum_likes', models.BigIntegerField(default=0, verbose_name='ไลก์สะสม')),
                ('cum_comments', models.BigIntegerField(default=0, verbose_name='คอมเมนต์สะสม')),
                ('cum_shares', models.BigIntegerField(default=0, verbose_name='แชร์สะสม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='คำนวณล่าสุด')),
            ],
            options={
                'verbose_name': 'ยอดโซเชียลรายวัน',
                'verbose_name_plural': 'ยอดโซเชียลรายวัน',
                'db_table': 'dash_social_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['platform', 'date'], name='dash_social_platfor_209680_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'object_id', 'date'), name='uniq_social_daily')],
            },
        ),
    ]
