# Generated by Django 5.0.14 on 2026-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_social_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ดึงเมื่อ')),
                ('kind', models.CharField(db_index=True, max_length=16, verbose_name='ชนิด')),
                ('channel_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ช่อง')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='คำตอบดิบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลดิบจาก YouTube',
                'verbose_name_plural': 'ข้อมูลดิบจาก YouTube',
                'db_table': 'dash_youtube_raw',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, verbose_name='ดึงเมื่อ')),
                ('snap_date', models.DateField(db_index=True, verbose_name='ยอด ณ สิ้นวัน')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('channel_id', models.CharField(db_index=True, max_length=64, verbose_name='ช่อง (UC...)')),
                ('handle', models.CharField(blank=True, max_length=120, verbose_name='@handle ที่ตั้งไว้ใน .env')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ชื่อช่อง')),
                ('subscriber_count', models.BigIntegerField(blank=True, null=True, verbose_name='ผู้ติดตาม')),
                ('view_count', models.BigIntegerField(blank=True, null=True, verbose_name='วิวรวมทั้งช่อง')),
                ('video_count', models.IntegerField(blank=True, null=True, verbose_name='จำนวนคลิป')),
            ],
            options={
                'verbose_name': 'ยอดช่อง YouTube (รายวัน)',
                'verbose_name_plural': 'ยอดช่อง YouTube (รายวัน)',
                'db_table': 'dash_youtube_channel_snapshot',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['channel_id', 'trigger', 'snap_date'], name='dash_youtub_channel_201564_idx')],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, verbose_name='ดึงเมื่อ')),
                ('snap_date', models.DateField(db_index=True, verbose_name='ยอดสะสม ณ สิ้นวัน')),
                ('trigger', models.CharField(default='cron', max_length=8, verbose_name='ดึงเพราะ')),
                ('channel_id', models.CharField(db_index=True, max_length=64, verbose_name='ช่อง (UC...)')),
                ('video_id', models.CharField(db_index=True, max_length=64, verbose_name='คลิป')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='โพสต์เมื่อ')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='ชื่อคลิป (ตัดสั้น)')),
                ('duration', models.IntegerField(default=0, verbose_name='ยาว (วินาที)')),
                ('is_short', models.BooleanField(default=False, verbose_name='เป็น Shorts (ยาว <= 3 นาที)')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='วิว')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='ไลก์')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='คอมเมนต์')),
            ],
            options={
                'verbose_name': 'ยอดคลิป YouTube (รายวัน)',
                'verbose_name_plural': 'ยอดคลิป YouTube (รายวัน)',
                'db_table': 'dash_youtube_video_snapshot',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['video_id', 'snap_date'], name='dash_youtub_video_i_a92b92_idx'), models.Index(fields=['channel_id', 'trigger', 'snap_date'], name='dash_youtub_channel_8326a8_idx')],
            },
        ),
    ]
