# Generated by Django 5.0.14 on 2026-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaaddaily',
            name='chats',
            field=models.IntegerField(default=0, verbose_name='เริ่มแชท (7 วัน)'),
        ),
        migrations.AddField(
            model_name='metaaddaily',
            name='chats_replied',
            field=models.IntegerField(default=0, verbose_name='แชทที่ตอบกลับ (7 วัน)'),
        ),
        migrations.AddField(
            model_name='metaaddaily',
            name='engagement',
            field=models.IntegerField(default=0, verbose_name='การมีส่วนร่วมกับโพสต์'),
        ),
        migrations.AddField(
            model_name='metaaddaily',
            name='leads',
            field=models.IntegerField(default=0, verbose_name='ลีด'),
        ),
        migrations.AddField(
            model_name='metaaddaily',
            name='link_clicks',
            field=models.IntegerField(default=0, verbose_name='คลิกลิงก์'),
        ),
        migrations.AddField(
            model_name='metaaddaily',
            name='video_views',
            field=models.IntegerField(default=0, verbose_name='วิววิดีโอ'),
        ),
        migrations.CreateModel(
            name='AdsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่')),
                ('account_id', models.CharField(db_index=True, max_length=32, verbose_name='บัญชีโฆษณา')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ใช้เงิน (บาท)')),
                ('impressions', models.BigIntegerField(default=0, verbose_name='แสดงผล')),
                ('reach', models.BigIntegerField(default=0, verbose_name='เข้าถึง (คน)')),
                ('clicks', models.BigIntegerField(default=0, verbose_name='คลิกทั้งหมด')),
                ('link_clicks', models.BigIntegerField(default=0, verbose_name='คลิกลิงก์')),
                ('video_views', models.BigIntegerField(default=0, verbose_name='วิววิดีโอ')),
                ('engagement', models.BigIntegerField(default=0, verbose_name='การมีส่วนร่วมกับโพสต์')),
                ('chats', models.BigIntegerField(default=0, verbose_name='เริ่มแชท')),
                ('chats_replied', models.BigIntegerField(default=0, verbose_name='แชทที่ตอบกลับ')),
                ('leads', models.BigIntegerField(default=0, verbose_name='ลีด')),
                ('ads', models.IntegerField(default=0, verbose_name='จำนวนโฆษณาที่ยิงวันนั้น')),
                ('campaigns', models.IntegerField(default=0, verbose_name='จำนวนแคมเปญ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='คำนวณล่าสุด')),
            ],
            options={
                'verbose_name': 'ยอดโฆษณารายวัน',
                'verbose_name_plural': 'ยอดโฆษณารายวัน',
                'db_table': 'dash_ads_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dash_ads_da_date_fcc568_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='adsdaily',
            constraint=models.UniqueConstraint(fields=('account_id', 'date'), name='uniq_ads_daily'),
        ),
    ]
