# Generated by Django 6.0.2 on 2026-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_ads_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=48, unique=True, verbose_name='รหัสรายการ')),
                ('redirect', models.CharField(max_length=300, verbose_name='ส่งกลับเข้าแอปที่')),
                ('challenge', models.CharField(max_length=128, verbose_name='PKCE challenge')),
                ('code_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='แฮชรหัสใช้ครั้งเดียว')),
                ('user', models.JSONField(blank=True, default=dict, verbose_name='คนที่ login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เริ่ม')),
                ('handed_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งรหัสกลับเข้าแอป')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='แลก token แล้ว')),
            ],
            options={
                'verbose_name': 'ใบผ่านทาง login แอปมือถือ',
                'verbose_name_plural': 'ใบผ่านทาง login แอปมือถือ',
                'db_table': 'dash_mobile_login',
            },
        ),
        migrations.CreateModel(
            name='MobileToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='แฮช token')),
                ('user', models.JSONField(blank=True, default=dict, verbose_name='คนที่ login')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ชื่อเล่น')),
                ('device', models.CharField(blank=True, max_length=160, verbose_name='เครื่อง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ออกเมื่อ')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ใช้ล่าสุด')),
                ('expires_at', models.DateTimeField(verbose_name='หมดอายุ')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='ยกเลิกเมื่อ')),
            ],
            options={
                'verbose_name': 'รหัสเข้าระบบแอปมือถือ',
                'verbose_name_plural': 'รหัสเข้าระบบแอปมือถือ',
                'db_table': 'dash_mobile_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
