# Generated by Django 5.0.6 on 2026-07-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0007_car_drive_folder_id_car_plate_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_line_group_id', models.CharField(max_length=64, unique=True, verbose_name='LINE group id')),
                ('name', models.CharField(max_length=80, verbose_name='ชื่อห้อง/สาขา')),
                ('active', models.BooleanField(default=True, verbose_name='เปิดใช้')),
                ('group_window_min', models.PositiveIntegerField(default=5, verbose_name='หน้าต่างจับกลุ่มไฟล์ (นาที)')),
                ('settle_seconds', models.PositiveIntegerField(default=90, verbose_name='รอไฟล์หยุดไหลก่อนตรวจ (วินาที)')),
                ('remind_after_min', models.PositiveIntegerField(default=5, verbose_name='ทวงหลังไม่ครบ (นาที)')),
                ('escalate_after_min', models.PositiveIntegerField(default=15, verbose_name='แจ้งหัวหน้าเมื่อเงียบเกิน (นาที)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'กติกาห้อง (checklist)',
                'verbose_name_plural': 'กติกาห้อง (checklist)',
            },
        ),
        migrations.CreateModel(
            name='LineEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_message_id', models.CharField(max_length=64, unique=True, verbose_name='LINE message id')),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='group id')),
                ('sender_line_id', models.CharField(blank=True, max_length=64, verbose_name='ผู้ส่ง')),
                ('event_type', models.CharField(blank=True, max_length=20, verbose_name='ชนิด event')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='event ดิบ')),
                ('status', models.CharField(choices=[('pending', 'รอโหลด'), ('done', 'โหลดแล้ว'), ('failed', 'ล้มเหลว'), ('skipped', 'ข้าม')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='ครั้งที่พยายามโหลด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LINE event (คิวโหลดไฟล์)',
                'verbose_name_plural': 'LINE event (คิวโหลดไฟล์)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(blank=True, max_length=30, verbose_name='ทะเบียนที่พิมพ์')),
                ('borrower_name', models.CharField(blank=True, max_length=80, verbose_name='ผู้เบิก/ผู้ขับ')),
                ('borrower_line_id', models.CharField(blank=True, max_length=64, verbose_name='LINE id ผู้เบิก')),
                ('purpose', models.CharField(blank=True, max_length=120, verbose_name='วัตถุประสงค์')),
                ('destination', models.CharField(blank=True, max_length=120, verbose_name='ปลายทาง/สาขา')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเบิก')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาคืน')),
                ('odo_out', models.PositiveIntegerField(blank=True, null=True, verbose_name='ไมล์ออก (OCR)')),
                ('odo_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='ไมล์เข้า (OCR)')),
                ('status', models.CharField(choices=[('waiting_files', 'รอไฟล์'), ('checking', 'กำลังตรวจ'), ('approved', 'ผ่าน (AI)'), ('incomplete', 'ไม่ครบ — ทวง'), ('pending_human', 'รอคนยืนยัน'), ('system_error', 'ระบบขัดข้อง — คนตรวจ'), ('approved_by_human', 'ผ่านโดยคน'), ('equipment_hold', 'ระงับ — อุปกรณ์เสีย'), ('cancelled', 'ยกเลิก')], default='waiting_files', max_length=20, verbose_name='สถานะ')),
                ('approved_by', models.CharField(blank=True, max_length=80, verbose_name='อนุมัติ/ผ่านโดย')),
                ('damage_reported', models.BooleanField(default=False, verbose_name='แจ้งความเสียหายตอนคืน')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='cars.car')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.checklistconfig')),
            ],
            options={
                'verbose_name': 'รอบเบิก-คืนรถ',
                'verbose_name_plural': 'รอบเบิก-คืนรถ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('key', models.CharField(max_length=40, verbose_name='คีย์')),
                ('label', models.CharField(max_length=80, verbose_name='ชื่อ')),
                ('media_type', models.CharField(choices=[('photo', 'รูป'), ('video', 'วิดีโอ')], default='photo', max_length=10, verbose_name='ชนิด')),
                ('required', models.BooleanField(default=True, verbose_name='บังคับ')),
                ('min_count', models.PositiveIntegerField(default=1, verbose_name='จำนวนขั้นต่ำ')),
                ('allow_from_group_shot', models.BooleanField(default=True, verbose_name='ยอมรับจากรูปรวมได้')),
                ('special_rule', models.CharField(blank=True, max_length=160, verbose_name='เงื่อนไขพิเศษ')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checklistconfig')),
            ],
            options={
                'verbose_name': 'ข้อ checklist',
                'verbose_name_plural': 'ข้อ checklist',
                'ordering': ['config', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(blank=True, max_length=80, verbose_name='ผู้แจ้ง')),
                ('issue', models.CharField(max_length=200, verbose_name='อาการ')),
                ('status', models.CharField(choices=[('open', 'รอจัดการ'), ('approved', 'อนุมัติให้ออก'), ('resolved', 'แก้แล้ว')], default='open', max_length=10, verbose_name='สถานะ')),
                ('approved_by', models.CharField(blank=True, max_length=80, verbose_name='อนุมัติโดย')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_issues', to='cars.car')),
            ],
            options={
                'verbose_name': 'แจ้งอุปกรณ์เสีย',
                'verbose_name_plural': 'แจ้งอุปกรณ์เสีย',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('out', 'เบิก'), ('in', 'คืน')], default='out', max_length=4, verbose_name='รอบ')),
                ('file', models.FileField(blank=True, null=True, upload_to='checkout/%Y/%m/', verbose_name='ไฟล์')),
                ('media_type', models.CharField(choices=[('photo', 'รูป'), ('video', 'วิดีโอ')], default='photo', max_length=10, verbose_name='ชนิด')),
                ('ai_label', models.CharField(blank=True, max_length=60, verbose_name='AI จำแนก')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='ความมั่นใจ AI')),
                ('phash', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='perceptual hash (กันรูปซ้ำ)')),
                ('line_message_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='LINE message id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.checklistitem')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkout.carmovement')),
            ],
            options={
                'verbose_name': 'ไฟล์หลักฐาน',
                'verbose_name_plural': 'ไฟล์หลักฐาน',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=80, verbose_name='ผู้ฝ่าฝืน')),
                ('person_line_id', models.CharField(blank=True, max_length=64, verbose_name='LINE id')),
                ('type', models.CharField(choices=[('no_evidence', 'ออกรถหลักฐานไม่ครบ'), ('ignored_reminder', 'เมินการทวง (เงียบเกินกำหนด)'), ('reused_photo', 'ใช้รูปซ้ำ/ของคนก่อน')], max_length=20, verbose_name='ประเภท')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='checkout.carmovement')),
            ],
            options={
                'verbose_name': 'บันทึกฝ่าฝืน',
                'verbose_name_plural': 'บันทึกฝ่าฝืน',
                'ordering': ['-created_at'],
            },
        ),
    ]
