# Generated by Django 5.0.14 on 2026-08-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmovement',
            name='fuel_requested',
            field=models.BooleanField(default=False, verbose_name='ขอเบิกน้ำมันด้วย'),
        ),
        migrations.AddField(
            model_name='carmovement',
            name='purpose_key',
            field=models.CharField(blank=True, max_length=20, verbose_name='ประเภทงาน'),
        ),
    ]
