# Generated by Django 5.0.14 on 2026-08-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_stage_alter_scanlog_stage'),
        ('checkout', '0002_carmovement_fuel_requested_carmovement_purpose_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=64, verbose_name='LINE group id')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='LINE message id')),
                ('sender_id', models.CharField(blank=True, max_length=64, verbose_name='LINE user id ผู้ส่ง')),
                ('sender_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อผู้ส่ง')),
                ('msg_type', models.CharField(blank=True, max_length=20, verbose_name='ชนิด')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('parsed_kind', models.CharField(blank=True, max_length=10, verbose_name='ตีความว่า')),
                ('parsed_plate', models.CharField(blank=True, max_length=20, verbose_name='ทะเบียนที่จับได้')),
                ('parsed_purpose', models.CharField(blank=True, max_length=20, verbose_name='ประเภทงานที่เดา')),
                ('parsed_conf', models.CharField(blank=True, max_length=10, verbose_name='ความมั่นใจ')),
                ('parsed_why', models.CharField(blank=True, max_length=120, verbose_name='เพราะอะไร')),
                ('human_verdict', models.CharField(blank=True, max_length=10, verbose_name='คนตรวจว่า')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาในกลุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
            ],
            options={
                'verbose_name': 'ข้อความในกลุ่ม (เฝ้าดู)',
                'verbose_name_plural': 'ข้อความในกลุ่ม (เฝ้าดู)',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
