# Generated by Django 5.0.14 on 2026-09-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_groupmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
