# Generated by Django 5.0.14 on 2026-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_drop_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmovement',
            name='source',
            field=models.CharField(choices=[('web', 'กดในเว็บ'), ('line', 'บอทอ่านจากกลุ่ม LINE'), ('import', 'นำเข้าจาก log')], db_index=True, default='web', max_length=10, verbose_name='ที่มา'),
        ),
    ]
