# Generated by Django 5.0.14 on 2026-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_movement_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmovement',
            name='shots_in',
            field=models.JSONField(blank=True, default=list, verbose_name='มุมที่ถ่ายตอนคืน'),
        ),
        migrations.AddField(
            model_name='carmovement',
            name='shots_out',
            field=models.JSONField(blank=True, default=list, verbose_name='มุมที่ถ่ายตอนเบิก'),
        ),
    ]
