# Generated by Django 5.0.14 on 2026-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_movement_shots'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=64, verbose_name='LINE group id')),
                ('group_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อกลุ่ม')),
                ('message_id', models.CharField(max_length=64, unique=True, verbose_name='LINE message id')),
                ('sender_id', models.CharField(blank=True, max_length=64, verbose_name='LINE user id ผู้ส่ง')),
                ('sender_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเล่นผู้ส่ง')),
                ('msg_type', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ชนิด')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('sticker_id', models.CharField(blank=True, max_length=32, verbose_name='sticker id')),
                ('sticker_package', models.CharField(blank=True, max_length=32, verbose_name='sticker package')),
                ('emojis', models.JSONField(blank=True, default=list, verbose_name='LINE emoji ในข้อความ')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลอื่นของ event')),
                ('has_media', models.BooleanField(db_index=True, default=False, verbose_name='มีไฟล์แนบ')),
                ('media_token', models.CharField(blank=True, max_length=200, verbose_name='ไฟล์ที่โหลดเก็บแล้ว')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='เวลาในกลุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แชทในกลุ่ม LINE',
                'verbose_name_plural': 'แชทในกลุ่ม LINE',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['group_id', '-sent_at'], name='checkout_gr_group_i_c12346_idx')],
            },
        ),
    ]
