# Generated by Django 5.0.14 on 2026-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='chat_type',
            field=models.CharField(choices=[('group', 'แชทกลุ่ม'), ('user', 'ลูกค้าทักเข้า OA'), ('room', 'ห้องคุย')], db_index=True, default='group', max_length=8, verbose_name='ประเภทแชท'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='LINE group id'),
        ),
    ]
