# Generated by Django 5.0.14 on 2026-09-11 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_chat_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True, verbose_name='LINE user id')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อที่ตั้งใน LINE')),
                ('picture_url', models.URLField(blank=True, max_length=500, verbose_name='รูปโปรไฟล์')),
                ('status_message', models.TextField(blank=True, verbose_name='สเตตัส')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='ภาษา')),
                ('nickname', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเล่น (จากชีตพนักงาน)')),
                ('is_employee', models.BooleanField(db_index=True, default=False, verbose_name='เป็นพนักงาน')),
                ('source', models.CharField(choices=[('user', 'ทักเข้า OA'), ('group', 'เจอในกลุ่ม'), ('room', 'ห้องคุย')], db_index=True, default='user', max_length=8, verbose_name='เจอครั้งแรกจาก')),
                ('group_id', models.CharField(blank=True, max_length=64, verbose_name='กลุ่มที่เจอ')),
                ('msg_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนข้อความที่เคยส่ง')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ทักครั้งแรก')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ล่าสุด')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='ดึงโปรไฟล์ล่าสุด')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='คำตอบดิบจาก LINE')),
            ],
            options={
                'verbose_name': 'โปรไฟล์คน LINE',
                'verbose_name_plural': 'โปรไฟล์คน LINE',
                'indexes': [models.Index(fields=['is_employee', '-last_seen'], name='checkout_li_is_empl_246094_idx')],
            },
        ),
    ]
