# Generated by Django 5.0.14 on 2026-09-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_lineprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineprofile',
            name='picture_url',
        ),
    ]
