# Generated by Django 5.0.14 on 2026-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_lineprofile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='บัญชีที่รับข้อความ'),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='เจอครั้งแรกจากบัญชี'),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='channels',
            field=models.JSONField(blank=True, default=list, verbose_name='เคยเห็นจากบัญชีไหนบ้าง'),
        ),
    ]
