# Generated by Django 5.0.14 on 2026-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_groupchat_channel_lineprofile_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='บัญชีที่รับข้อความ'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='เจอครั้งแรกจากบัญชี'),
        ),
    ]
