# Generated by Django 5.0.14 on 2026-09-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_oa_key_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True, verbose_name='ชื่อเล่น')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ชื่อที่ตั้งใน LINE')),
                ('position', models.CharField(blank=True, max_length=80, verbose_name='ตำแหน่ง/ทีม')),
                ('work_start', models.CharField(blank=True, max_length=16, verbose_name='เวลาเข้างาน')),
                ('day_off', models.CharField(blank=True, max_length=40, verbose_name='วันหยุด')),
                ('group_id', models.CharField(blank=True, max_length=64, verbose_name='กลุ่ม LINE ที่ผูกไว้')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ยังทำงานอยู่')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('source', models.CharField(choices=[('sheet', 'นำเข้าจากชีต'), ('manual', 'เพิ่มในระบบ')], default='manual', max_length=8, verbose_name='ที่มา')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
                'ordering': ['position', 'nickname'],
            },
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_accounts', to='checkout.employee', verbose_name='เป็นพนักงานคนนี้'),
        ),
    ]
