# Generated by Django 5.0.14 on 2026-09-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_employee_lineprofile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='LINE user id ที่ส่งมา')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อที่โชว์')),
                ('date_iso', models.DateField(db_index=True, verbose_name='วันที่ (โซนไทย)')),
                ('checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเช็คชื่อ')),
                ('time_hm', models.CharField(blank=True, max_length=8, verbose_name='เวลาที่อ่านได้')),
                ('work_start', models.CharField(blank=True, max_length=16, verbose_name='เวลาเข้างานที่ใช้ตัดสิน')),
                ('status', models.CharField(choices=[('ontime', 'ตรงเวลา'), ('late', 'สาย'), ('abnormal', 'ผิดปกติ/อ่านไม่ออก')], db_index=True, default='abnormal', max_length=10, verbose_name='สถานะ')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='เหตุผล')),
                ('time_source', models.CharField(blank=True, max_length=16, verbose_name='เวลามาจาก')),
                ('full_address', models.CharField(blank=True, max_length=300, verbose_name='สถานที่')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='จังหวัด')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลดิบที่ AI อ่านได้')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='checkout.employee', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'เช็คชื่อเข้างาน',
                'verbose_name_plural': 'เช็คชื่อเข้างาน',
                'ordering': ['-date_iso', 'time_hm'],
                'indexes': [models.Index(fields=['-date_iso', 'status'], name='checkout_ch_date_is_5365b4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('user_id', 'date_iso'), name='uniq_checkin_user_day'),
        ),
    ]
