# Generated by Django 5.0.14 on 2026-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_employee_track_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='source',
            field=models.CharField(choices=[('sheet', 'นำเข้าจากชีต'), ('manual', 'เพิ่มในระบบ'), ('auto', 'ระบบเพิ่มให้ตอนเจอในกลุ่ม')], default='manual', max_length=8, verbose_name='ที่มา'),
        ),
    ]
