# Generated by Django 5.0.14 on 2026-09-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_employee_auto_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notify_missing',
            field=models.BooleanField(db_index=True, default=False, verbose_name='แท็กเวลามีคนไม่เช็คชื่อ'),
        ),
    ]
