# Generated by Django 6.0.2 on 2026-09-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_employee_notify_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='direction',
            field=models.CharField(choices=[('in', 'ลูกค้าส่งมา'), ('out', 'เราตอบไป')], db_index=True, default='in', max_length=4, verbose_name='ทิศทาง'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='send_error',
            field=models.CharField(blank=True, max_length=200, verbose_name='ส่งไม่สำเร็จเพราะ'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='checkout.employee', verbose_name='คนตอบ'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='sent_by_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='ชื่อคนตอบ'),
        ),
        migrations.CreateModel(
            name='CustomerNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_text', models.CharField(blank=True, max_length=300, verbose_name='ที่ลูกค้าพิมพ์มา')),
                ('car_model', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='รุ่นที่จับได้')),
                ('car_year_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ปีตั้งแต่')),
                ('car_year_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ปีถึง')),
                ('budget_max', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='งบสูงสุด (บาท)')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='งบต่ำสุด (บาท)')),
                ('monthly_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='ผ่อนไหวเดือนละ (บาท)')),
                ('down_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='ดาวน์ได้ (บาท)')),
                ('status', models.CharField(choices=[('new', 'เพิ่งถามเข้ามา'), ('lead', 'เป็นลีดแล้ว (มีเซลล์ตาม)'), ('booked', 'จองแล้ว'), ('won', 'ปิดการขายได้'), ('rj', 'ไม่ได้ไปต่อ (RJ)')], db_index=True, default='new', max_length=8, verbose_name='สถานะ')),
                ('reject_kind', models.CharField(blank=True, choices=[('price', 'ราคา/งบไม่ลงตัว'), ('nocar', 'ไม่มีรถรุ่นที่ต้องการ'), ('credit', 'เครดิต/ไฟแนนซ์ไม่ผ่าน'), ('lost', 'ซื้อที่อื่น/ได้รถแล้ว'), ('silent', 'ติดต่อไม่ได้/เงียบไป'), ('other', 'อื่นๆ')], db_index=True, max_length=8, verbose_name='RJ เพราะ')),
                ('reject_note', models.CharField(blank=True, max_length=300, verbose_name='รายละเอียดที่ปิดเคส')),
                ('waiting', models.BooleanField(db_index=True, default=False, verbose_name='รอรถที่ตรงสเปกอยู่')),
                ('lead_code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='รหัสลีด (ถ้ามี)')),
                ('seller', models.CharField(blank=True, max_length=80, verbose_name='เซลล์ที่ดูแล')),
                ('source', models.CharField(choices=[('chat', 'จับจากแชทลูกค้า'), ('manual', 'แอดมินกรอกเอง'), ('group', 'จากกลุ่มจ่ายเบอร์')], default='chat', max_length=8, verbose_name='ที่มา')),
                ('evidence', models.TextField(blank=True, verbose_name='ข้อความที่ใช้สรุป')),
                ('confidence', models.CharField(blank=True, max_length=8, verbose_name='ความมั่นใจ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='บันทึกเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ล่าสุด')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='เจอรถที่ตรง')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='checkout.lineprofile', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'ความต้องการลูกค้า',
                'verbose_name_plural': 'ความต้องการลูกค้า',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['waiting', 'car_model'], name='checkout_cu_waiting_f1b7dd_idx'), models.Index(fields=['status', '-updated_at'], name='checkout_cu_status_bf12b3_idx')],
            },
        ),
    ]
