# Generated by Django 6.0.2 on 2026-09-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_groupchat_direction_groupchat_send_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerneed',
            name='channel',
            field=models.CharField(blank=True, max_length=80, verbose_name='ช่องทางที่ได้ลีดมา'),
        ),
        migrations.AddField(
            model_name='customerneed',
            name='contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='เบอร์/ไลน์ไอดีที่ให้ไว้'),
        ),
        migrations.AddField(
            model_name='customerneed',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='ชื่อลูกค้า (เคสจากกลุ่ม)'),
        ),
        migrations.AlterField(
            model_name='customerneed',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='checkout.lineprofile', verbose_name='ลูกค้า'),
        ),
    ]
