# Generated by Django 6.0.2 on 2026-09-19 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_customerneed_channel_customerneed_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('user', 'ลูกค้าทักเข้าเพจ')], db_index=True, default='user', max_length=8, verbose_name='ประเภทแชท')),
                ('thread_id', models.CharField(db_index=True, max_length=64, verbose_name='ห้องสนทนา (t_…)')),
                ('message_id', models.CharField(max_length=160, unique=True, verbose_name='message id')),
                ('sender_id', models.CharField(blank=True, max_length=64, verbose_name='PSID ผู้ส่ง')),
                ('sender_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อผู้ส่ง')),
                ('msg_type', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ชนิด')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('sticker_id', models.CharField(blank=True, max_length=300, verbose_name='สติกเกอร์')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลดิบของข้อความ')),
                ('has_media', models.BooleanField(db_index=True, default=False, verbose_name='มีไฟล์แนบ')),
                ('media_token', models.CharField(blank=True, max_length=200, verbose_name='ไฟล์ที่โหลดเก็บแล้ว')),
                ('channel', models.CharField(blank=True, db_index=True, max_length=24, verbose_name='เพจ')),
                ('direction', models.CharField(choices=[('in', 'ลูกค้าส่งมา'), ('out', 'เพจตอบไป')], db_index=True, default='in', max_length=4, verbose_name='ทิศทาง')),
                ('sent_by_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อคนตอบ')),
                ('send_error', models.CharField(blank=True, max_length=200, verbose_name='ส่งไม่สำเร็จเพราะ')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='เวลาที่ส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_replies', to='checkout.employee', verbose_name='คนตอบ')),
            ],
            options={
                'verbose_name': 'แชท Facebook Messenger',
                'verbose_name_plural': 'แชท Facebook Messenger',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['thread_id', '-sent_at'], name='checkout_fb_thread__ecdfc0_idx'), models.Index(fields=['channel', '-sent_at'], name='checkout_fb_channel_27147b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FbProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='PSID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อใน Facebook')),
                ('nickname', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเล่น (ถ้าเป็นพนักงาน)')),
                ('is_employee', models.BooleanField(db_index=True, default=False, verbose_name='เป็นพนักงาน')),
                ('source', models.CharField(choices=[('user', 'ทักเข้าเพจ')], default='user', max_length=8, verbose_name='เจอครั้งแรกจาก')),
                ('channel', models.CharField(db_index=True, max_length=24, verbose_name='เพจ')),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ห้องสนทนา (t_…)')),
                ('inbox_link', models.CharField(blank=True, max_length=300, verbose_name='ลิงก์เปิดใน Inbox')),
                ('thread_updated', models.DateTimeField(blank=True, null=True, verbose_name='ห้องขยับล่าสุด (ตอนดึง)')),
                ('msg_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนข้อความในห้อง')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ทักครั้งแรก (เท่าที่ดึงได้)')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ล่าสุด')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='ดึงล่าสุด')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='คำตอบดิบจาก Meta')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_accounts', to='checkout.employee', verbose_name='เป็นพนักงานคนนี้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์คน Facebook',
                'verbose_name_plural': 'โปรไฟล์คน Facebook',
                'indexes': [models.Index(fields=['is_employee', '-last_seen'], name='checkout_fb_is_empl_61263a_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'user_id'), name='uniq_fbprofile_page_psid')],
            },
        ),
    ]
