# Generated by Django 6.0.2 on 2026-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_auto_employee_no_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='note_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เขียนหมายเหตุ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='note_sticky',
            field=models.BooleanField(default=False, verbose_name='หมายเหตุค้างไว้จนกว่าจะลบ'),
        ),
    ]
