# Generated by Django 6.0.2 on 2026-09-27 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_employee_note_date_employee_note_sticky'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=64, unique=True, verbose_name='LINE group id')),
                ('name', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='ชื่อกลุ่ม')),
                ('kind', models.CharField(choices=[('coaching', 'ห้องโค้ชเซลล์ (Senior/Junior)'), ('lead', 'จ่ายเบอร์ / จ่ายลีด'), ('tradein', 'ซื้อ-ขาย / เทิร์นรถ'), ('booking', 'จองรถ'), ('purchase', 'จัดซื้อ / รับรถเข้า'), ('finance', 'จัดไฟแนนซ์'), ('transfer', 'รับ-ส่งระหว่างสาขา'), ('checkin', 'เช็คชื่อเข้างาน'), ('admin', 'ทีมแอดมิน / ออฟฟิศ'), ('content', 'คอนเทนต์ / การตลาด'), ('hr', 'รับสมัครงาน / บุคคล'), ('other', 'อื่นๆ / ยังไม่จัดหมวด')], db_index=True, default='other', max_length=16, verbose_name='ประเภทงาน')),
                ('kind_auto', models.BooleanField(default=True, verbose_name='ประเภทนี้ระบบเดาให้')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='บัญชีบอทที่อยู่ในกลุ่มนี้')),
                ('source', models.CharField(blank=True, max_length=12, verbose_name='ที่มา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ยังใช้งานอยู่')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='รู้จักครั้งแรก')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ได้ยินล่าสุด')),
            ],
            options={
                'verbose_name': 'กลุ่ม LINE',
                'verbose_name_plural': 'กลุ่ม LINE',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
