# Generated by Django 6.0.2 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_linegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=120, unique=True, verbose_name='รหัสอ้างอิง')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='เมื่อไหร่')),
                ('date_text', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='วันที่')),
                ('time_text', models.CharField(blank=True, max_length=8, verbose_name='เวลา')),
                ('case_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='รหัสเคส')),
                ('who', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ผู้พูด')),
                ('role', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='บทบาท')),
                ('team', models.CharField(blank=True, max_length=40, verbose_name='ทีม')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('case_status', models.CharField(blank=True, max_length=80, verbose_name='สถานะเคส')),
                ('kind', models.CharField(blank=True, max_length=40, verbose_name='ชนิด')),
                ('source', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ที่มา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'บันทึกห้องโค้ช',
                'verbose_name_plural': 'บันทึกห้องโค้ช',
                'ordering': ['sent_at', 'id'],
                'indexes': [models.Index(fields=['role', 'sent_at'], name='checkout_co_role_36fcc6_idx')],
            },
        ),
    ]
