# Generated by Django 6.0.2 on 2026-10-03 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_coachlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='ทีม')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='รับลูกค้าเมื่อ')),
                ('first_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='เจ้าของปัจจุบันตอบครั้งแรก')),
                ('awaiting_since', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ลูกค้ารอคำตอบตั้งแต่')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ต้องตอบภายใน')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='แจ้งแอดมินว่าเลยเวลาเมื่อ')),
                ('last_in_at', models.DateTimeField(blank=True, null=True, verbose_name='ลูกค้าส่งล่าสุด')),
                ('last_out_at', models.DateTimeField(blank=True, null=True, verbose_name='เราตอบล่าสุด')),
                ('last_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ขยับล่าสุด')),
                ('last_preview', models.CharField(blank=True, max_length=200, verbose_name='ข้อความล่าสุด')),
                ('last_dir', models.CharField(blank=True, max_length=4, verbose_name='ข้อความล่าสุดเป็นของ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_customers', to='checkout.employee', verbose_name='เซลล์ที่ดูแล')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_row', to='checkout.lineprofile', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'Connect — เจ้าของลูกค้า',
                'verbose_name_plural': 'Connect — เจ้าของลูกค้า',
                'ordering': ['-last_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatOwnerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claim', 'รับลูกค้า'), ('assign', 'แอดมินโอนให้'), ('release', 'ปล่อยคืนคิว'), ('escalate', 'เลยเวลา แจ้งแอดมิน'), ('reply', 'ตอบลูกค้า'), ('dismiss', 'ไม่ต้องตอบ')], db_index=True, max_length=12, verbose_name='เหตุการณ์')),
                ('emp_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเซลล์')),
                ('by_name', models.CharField(blank=True, max_length=80, verbose_name='คนสั่ง')),
                ('team', models.CharField(blank=True, max_length=8, verbose_name='ทีม')),
                ('wait_sec', models.IntegerField(blank=True, null=True, verbose_name='ลูกค้ารอ (วินาที)')),
                ('on_time', models.BooleanField(blank=True, null=True, verbose_name='ทันเวลา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='เมื่อ')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checkout.chatowner', verbose_name='ลูกค้า')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='checkout.employee', verbose_name='เซลล์ที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'Connect — ประวัติ',
                'verbose_name_plural': 'Connect — ประวัติ',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['action', '-at'], name='checkout_ch_action_0ec2d5_idx')],
            },
        ),
    ]
