# Generated by Django 6.0.2 on 2026-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatowner',
            name='picture_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ดึงโปรไฟล์ล่าสุด'),
        ),
        migrations.AddField(
            model_name='chatowner',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='รูปโปรไฟล์ LINE (ลิงก์)'),
        ),
    ]
