# Generated by Django 6.0.2 on 2026-10-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_connect_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Code (เลขลีด)')),
                ('lead_type', models.CharField(blank=True, max_length=40, verbose_name='type')),
                ('ads', models.CharField(blank=True, max_length=120, verbose_name='ADS')),
                ('account', models.CharField(blank=True, max_length=120, verbose_name='ชื่อ Account')),
                ('channel', models.CharField(blank=True, max_length=80, verbose_name='ช่องทาง')),
                ('branch', models.CharField(blank=True, max_length=60, verbose_name='สาขา')),
                ('live_team', models.CharField(blank=True, max_length=60, verbose_name='ทีมไลฟ์')),
                ('admin_name', models.CharField(blank=True, max_length=60, verbose_name='Admin')),
                ('focus', models.CharField(blank=True, max_length=60, verbose_name='FOCUS')),
                ('car_text', models.CharField(blank=True, max_length=300, verbose_name='รถลูกค้าถาม')),
                ('car_model', models.CharField(blank=True, max_length=80, verbose_name='CAR / สูตร')),
                ('call_proof', models.CharField(blank=True, max_length=20, verbose_name='แจ้งหลักฐานการโทร')),
                ('fill_note', models.TextField(blank=True, verbose_name='มากรอกชีตกันเถอะ')),
                ('admin_profile', models.TextField(blank=True, verbose_name='PROFILE ลูกค้า จาก ADMIN')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อลูกค้า')),
                ('line_id', models.CharField(blank=True, max_length=80, verbose_name='ID LINE')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='เบอร์โทร')),
                ('occupation', models.CharField(blank=True, max_length=80, verbose_name='อาชีพ')),
                ('income', models.CharField(blank=True, max_length=60, verbose_name='รายได้')),
                ('job_tenure', models.CharField(blank=True, max_length=60, verbose_name='อายุงาน')),
                ('pay_history', models.CharField(blank=True, max_length=120, verbose_name='ประวัติการผ่อน')),
                ('customer_type', models.CharField(blank=True, max_length=60, verbose_name='ประเภทลูกค้า')),
                ('live', models.CharField(blank=True, max_length=60, verbose_name='ไลฟ์')),
                ('more', models.TextField(blank=True, verbose_name='เพิ่มเติม')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='แท็ก')),
                ('auto', models.JSONField(blank=True, default=dict, verbose_name='ช่องที่ระบบเติมให้')),
                ('updated_by', models.CharField(blank=True, max_length=80, verbose_name='แก้ล่าสุดโดย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='checkout.chatowner', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'Connect — ข้อมูลลีดของลูกค้า',
                'verbose_name_plural': 'Connect — ข้อมูลลีดของลูกค้า',
            },
        ),
    ]
