# Generated by Django 6.0.2 on 2026-10-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_connect_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='จ่ายเบอร์เมื่อ'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=80, verbose_name='จ่ายเบอร์โดย'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='code_demo',
            field=models.BooleanField(default=False, verbose_name='เลขลีดออกในโหมดทดลอง'),
        ),
    ]
