# Generated by Django 6.0.2 on 2026-10-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0028_connect_assign_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, unique=True, verbose_name='ข้อความใบร่าง (LINE message id)')),
                ('group_id', models.CharField(blank=True, max_length=64, verbose_name='กลุ่ม')),
                ('group_name', models.CharField(blank=True, max_length=160, verbose_name='ชื่อกลุ่ม')),
                ('parked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='พักเมื่อ')),
                ('parked_by', models.CharField(blank=True, max_length=80, verbose_name='พักโดย')),
                ('source', models.CharField(blank=True, max_length=16, verbose_name='ช่องทางหลัก')),
                ('prefix', models.CharField(blank=True, max_length=16, verbose_name='ตัวหน้าในใบร่าง')),
                ('account', models.CharField(blank=True, max_length=120, verbose_name='ชื่อ Account')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อลูกค้า')),
                ('line_id', models.CharField(blank=True, max_length=80, verbose_name='ID LINE')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='เบอร์โทร')),
                ('channel', models.CharField(blank=True, max_length=80, verbose_name='ช่องทาง')),
                ('car_text', models.CharField(blank=True, max_length=300, verbose_name='รถ')),
                ('live', models.CharField(blank=True, max_length=60, verbose_name='ไลฟ์')),
                ('ads', models.CharField(blank=True, max_length=120, verbose_name='Ads')),
                ('more', models.TextField(blank=True, verbose_name='เพิ่มเติม')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Code (เลขลีด)')),
                ('code_demo', models.BooleanField(default=False, verbose_name='เลขลีดออกในโหมดทดลอง')),
                ('seller_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเซลล์ (ตอนจ่าย)')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='จ่ายเบอร์เมื่อ')),
                ('assigned_by', models.CharField(blank=True, max_length=80, verbose_name='จ่ายเบอร์โดย')),
                ('no_code', models.BooleanField(default=False, verbose_name='ไม่ต้องจ่ายเบอร์')),
                ('no_code_by', models.CharField(blank=True, max_length=80, verbose_name='กดไม่ต้องจ่ายโดย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_leads', to='checkout.employee', verbose_name='จ่ายให้เซลล์')),
            ],
            options={
                'verbose_name': 'ลีดภายนอก (ห้องพัก Lead)',
                'verbose_name_plural': 'ลีดภายนอก (ห้องพัก Lead)',
                'ordering': ['-parked_at', '-id'],
            },
        ),
    ]
