# Generated by Django 6.0.2 on 2026-10-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0029_ext_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatowner',
            name='fb_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_row', to='checkout.fbprofile', verbose_name='ลูกค้า (Facebook)'),
        ),
        migrations.AlterField(
            model_name='chatowner',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_row', to='checkout.lineprofile', verbose_name='ลูกค้า'),
        ),
    ]
