# Generated by Django 6.0.2 on 2026-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0031_lead_post_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='customer_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='สถานะลูกค้า'),
        ),
    ]
