# Generated by Django 6.0.2 on 2026-10-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0033_chatowner_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10, verbose_name='เบอร์ (ตัวเลขล้วน)')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='เลขลีด')),
                ('seller', models.CharField(blank=True, max_length=80, verbose_name='เซลล์')),
                ('channel', models.CharField(blank=True, max_length=80, verbose_name='ช่องทาง')),
                ('car', models.CharField(blank=True, max_length=120, verbose_name='รถที่ถาม')),
                ('seen_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='วันที่เป็นลีด')),
                ('source', models.CharField(choices=[('sheet', 'ชีตลีด'), ('slip', 'ใบจ่ายลีดในกลุ่ม'), ('system', 'ปุ่มจ่ายเบอร์ในระบบ')], default='sheet', max_length=8, verbose_name='ที่มา')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สมุดเบอร์ลูกค้า',
                'verbose_name_plural': 'สมุดเบอร์ลูกค้า',
                'constraints': [models.UniqueConstraint(fields=('phone', 'code', 'source'), name='uniq_leadphone')],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='เลขลีด')),
                ('run', models.CharField(db_index=True, max_length=12, verbose_name='เลขรัน (ที่เซลล์พิมพ์)')),
                ('source', models.CharField(default='system', max_length=8, verbose_name='ที่มา')),
                ('seller_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเซลล์')),
                ('by', models.CharField(blank=True, max_length=80, verbose_name='จ่ายโดย')),
                ('customer', models.CharField(blank=True, max_length=120, verbose_name='ลูกค้า')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='เบอร์')),
                ('car', models.CharField(blank=True, max_length=120, verbose_name='รถ')),
                ('group_id', models.CharField(blank=True, max_length=64, verbose_name='กลุ่มที่ใบอยู่')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ใบถึงกลุ่มเมื่อ')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ต้องรายงานผลภายใน')),
                ('acked_at', models.DateTimeField(blank=True, null=True, verbose_name='กดรับเคสเมื่อ')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='กดขอผ่านเมื่อ')),
                ('first_report_at', models.DateTimeField(blank=True, null=True, verbose_name='รายงานผลครั้งแรก')),
                ('last_report_at', models.DateTimeField(blank=True, null=True, verbose_name='รายงานผลล่าสุด')),
                ('reports', models.PositiveIntegerField(default=0, verbose_name='รายงานกี่ครั้ง')),
                ('last_report', models.CharField(blank=True, max_length=300, verbose_name='รายงานล่าสุด')),
                ('overdue_at', models.DateTimeField(blank=True, null=True, verbose_name='เลยเวลาเมื่อ')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='เปลี่ยนมือ')),
                ('card', models.JSONField(blank=True, default=dict, verbose_name='ผลส่งการ์ดปุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to='checkout.chatowner', verbose_name='ลูกค้าแชท')),
                ('ext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to='checkout.extlead', verbose_name='ลีดภายนอก')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to='checkout.employee', verbose_name='เซลล์')),
            ],
            options={
                'verbose_name': 'งานจ่ายเบอร์ (นาฬิการายงานผล)',
                'verbose_name_plural': 'งานจ่ายเบอร์ (นาฬิการายงานผล)',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, unique=True, verbose_name='ข้อความ (LINE message id)')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='เลขลีด')),
                ('seller_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อเซลล์')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ส่งเมื่อ')),
                ('fields', models.JSONField(blank=True, default=dict, verbose_name='อ่านได้')),
                ('state', models.CharField(choices=[('noted', 'จดไว้เฉยๆ'), ('asked', 'ส่งการ์ดยืนยันแล้ว'), ('saved', 'เซลล์ยืนยัน ลงชีตแล้ว'), ('skipped', 'เซลล์กดไม่บันทึก'), ('failed', 'ส่งการ์ด/ลงชีตไม่สำเร็จ')], db_index=True, default='noted', max_length=8, verbose_name='สถานะ')),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('saved', models.JSONField(blank=True, default=dict, verbose_name='ผลลงชีต')),
                ('appt_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='นัดลูกค้า')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='เตือนนัดแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reports', to='checkout.employee', verbose_name='เซลล์')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_rows', to='checkout.leadtask', verbose_name='งานจ่ายเบอร์')),
            ],
            options={
                'verbose_name': 'รายงานผลจากห้องจ่ายเบอร์',
                'verbose_name_plural': 'รายงานผลจากห้องจ่ายเบอร์',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
