# Generated by Django 5.2.15 on 2026-06-22 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='รหัสสาขา (prefix)')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อสาขา')),
                ('active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
            ],
            options={
                'verbose_name': 'สาขา',
                'verbose_name_plural': 'สาขา',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('code', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='รหัสรถ')),
                ('branch', models.CharField(default='CB', max_length=4, verbose_name='สาขา')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='ทะเบียน')),
                ('brand', models.CharField(blank=True, max_length=40, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(blank=True, max_length=60, verbose_name='รุ่น')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปี')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='สี')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='เลขไมล์')),
                ('stage', models.CharField(choices=[('intake', 'รับเข้า'), ('appraise', 'ประเมินซ่อม'), ('repair', 'เช็คซ่อม'), ('wait_paint', 'รอเข้าอู่สี'), ('paint', 'ทำสี/อู่สี'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('film', 'ติดฟิล์ม'), ('detail', 'ชง/ล้าง (ดีเทล)'), ('qc', 'รอตรวจ (QC)'), ('rework', 'รอแก้ไข (ไม่ผ่าน)'), ('registration', 'ทะเบียน (โอน/ภาษี/พ.ร.บ./ป้าย)'), ('show', 'รถพร้อมขาย/หน้าร้าน'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('sold', 'ขายแล้ว')], default='intake', max_length=20, verbose_name='สเตป')),
                ('stage_since', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เข้าสเตปเมื่อ')),
                ('date_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันรับเข้า')),
                ('frontline_at', models.DateTimeField(blank=True, null=True, verbose_name='ขึ้นหน้าร้านเมื่อ')),
                ('status', models.CharField(choices=[('active', 'กำลังดำเนินการ'), ('sold', 'ขายแล้ว'), ('hold', 'พัก/ระงับ (รถบริษัท/CEO/ยืม)')], default='active', max_length=10, verbose_name='สถานะ')),
                ('book_status', models.CharField(blank=True, choices=[('', '— เลือกสถานะเล่ม —'), ('ready', 'พร้อมเล่ม'), ('waiting', 'รอเล่ม'), ('transferring', 'ระหว่างโอน'), ('copy', 'ใช้สำเนา'), ('finance', 'ติดไฟแนนซ์')], max_length=14, verbose_name='สถานะเล่ม')),
                ('tax_due_date', models.DateField(blank=True, null=True, verbose_name='ครบกำหนดต่อภาษี')),
                ('doc_registration', models.FileField(blank=True, null=True, upload_to='docs/%Y/%m/', verbose_name='เล่มทะเบียน')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/', verbose_name='รูปรถ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รถ',
                'verbose_name_plural': 'รถ',
                'ordering': ['-date_in'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('intake', 'รับเข้า'), ('appraise', 'ประเมินซ่อม'), ('repair', 'เช็คซ่อม'), ('wait_paint', 'รอเข้าอู่สี'), ('paint', 'ทำสี/อู่สี'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('film', 'ติดฟิล์ม'), ('detail', 'ชง/ล้าง (ดีเทล)'), ('qc', 'รอตรวจ (QC)'), ('rework', 'รอแก้ไข (ไม่ผ่าน)'), ('registration', 'ทะเบียน (โอน/ภาษี/พ.ร.บ./ป้าย)'), ('show', 'รถพร้อมขาย/หน้าร้าน'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('sold', 'ขายแล้ว')], max_length=20, verbose_name='สเตป')),
                ('worker_name', models.CharField(blank=True, max_length=80, verbose_name='ผู้สแกน')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='LINE userId')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/', verbose_name='รูป')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cars.car', verbose_name='รถ')),
            ],
            options={
                'verbose_name': 'ประวัติการสแกน',
                'verbose_name_plural': 'ประวัติการสแกน',
                'ordering': ['-created_at'],
            },
        ),
    ]
