# Generated by Django 5.0.14 on 2026-06-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลเพิ่มเติม (นำเข้า)'),
        ),
    ]
