# Generated by Django 5.0.14 on 2026-06-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ลบเมื่อ (ถังขยะ)'),
        ),
    ]
