# Generated by Django 5.0.14 on 2026-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='media',
            field=models.JSONField(blank=True, default=list, verbose_name='ไฟล์แนบ (รูป/วิดีโอ)'),
        ),
    ]
