# Generated by Django 5.0.14 on 2026-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_scanlog_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('identity', models.CharField(blank=True, max_length=200, verbose_name='บัญชี (user/LINE id)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อ')),
                ('method', models.CharField(blank=True, choices=[('line', 'LINE'), ('admin', 'แอดมินรหัสผ่าน'), ('worker', 'บัญชีรหัสผ่าน')], max_length=20, verbose_name='วิธี')),
                ('success', models.BooleanField(default=True, verbose_name='สำเร็จ')),
                ('role', models.CharField(blank=True, max_length=40, verbose_name='บทบาท')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='อุปกรณ์')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ/สาเหตุ')),
            ],
            options={
                'verbose_name': 'การเข้าสู่ระบบ',
                'verbose_name_plural': 'การเข้าสู่ระบบ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='cars_logine_created_1c62c7_idx'), models.Index(fields=['success'], name='cars_logine_success_73c984_idx')],
            },
        ),
    ]
