# Generated by Django 5.0.14 on 2026-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_loginevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('page', models.CharField(blank=True, max_length=20)),
                ('last_seen', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'ออนไลน์',
                'verbose_name_plural': 'ออนไลน์',
                'ordering': ['-last_seen'],
            },
        ),
    ]
