# Generated by Django 5.0.6 on 2026-06-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='โฟลเดอร์ Drive'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_original',
            field=models.CharField(blank=True, max_length=20, verbose_name='ทะเบียนเดิม (ก่อนแก้)'),
        ),
    ]
