# Generated by Django 5.0.6 on 2026-07-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_restage_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('repair', 'เช็คซ่อม'), ('qc_repair', 'ซ่อมเสร็จ รอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint', 'ทำสี/อู่สี'), ('qc_paint', 'สีเสร็จ รอตรวจ'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('qc_wash', 'ล้างเสร็จ รอตรวจ'), ('show', 'รถพร้อมขาย/หน้าร้าน'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('sold', 'ขายแล้ว')], default='intake', max_length=20, verbose_name='สเตป'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('repair', 'เช็คซ่อม'), ('qc_repair', 'ซ่อมเสร็จ รอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint', 'ทำสี/อู่สี'), ('qc_paint', 'สีเสร็จ รอตรวจ'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('qc_wash', 'ล้างเสร็จ รอตรวจ'), ('show', 'รถพร้อมขาย/หน้าร้าน'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('sold', 'ขายแล้ว')], max_length=20, verbose_name='สเตป'),
        ),
    ]
