# Generated by Django 5.0.14 on 2026-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_work_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('photo_wait', 'รถรอถ่ายรูป'), ('repair', 'เช็คซ่อม'), ('repair_done', 'ซ่อมเสร็จรอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint_in', 'อู่สีใน'), ('paint_out', 'อู่สีนอก'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('qc_show', 'รอ QC ตรวจ'), ('sales_check', 'รอเซลล์ตรวจรถขึ้นโชว์'), ('show', 'รถพร้อมขาย (ตรวจรถขึ้นโชว์)'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('qc_release', 'ตรวจรถรอปล่อย'), ('release', 'ปล่อยรถ (ส่งรูปปล่อยรถ)')], default='intake', max_length=20, verbose_name='สเตป'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('photo_wait', 'รถรอถ่ายรูป'), ('repair', 'เช็คซ่อม'), ('repair_done', 'ซ่อมเสร็จรอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint_in', 'อู่สีใน'), ('paint_out', 'อู่สีนอก'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('qc_show', 'รอ QC ตรวจ'), ('sales_check', 'รอเซลล์ตรวจรถขึ้นโชว์'), ('show', 'รถพร้อมขาย (ตรวจรถขึ้นโชว์)'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('closing', 'รอปิดการขาย'), ('qc_release', 'ตรวจรถรอปล่อย'), ('release', 'ปล่อยรถ (ส่งรูปปล่อยรถ)')], max_length=20, verbose_name='สเตป'),
        ),
    ]
