# Generated by Django 5.0.14 on 2026-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_car_stage_alter_scanlog_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='need_tire',
            field=models.BooleanField(default=False, verbose_name='รอเปลี่ยนยาง'),
        ),
        migrations.AlterField(
            model_name='car',
            name='need_content',
            field=models.BooleanField(default=True, verbose_name='ยังไม่ได้ถ่ายคอนเทนต์'),
        ),
        migrations.AlterField(
            model_name='car',
            name='need_photo',
            field=models.BooleanField(default=True, verbose_name='ยังไม่ได้ถ่ายรูป'),
        ),
    ]
