# Generated by Django 5.0.14 on 2026-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_car_need_tire_alter_car_need_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('photo_wait', 'รถรอถ่ายรูป'), ('repair', 'เช็คซ่อม'), ('repair_done', 'ซ่อมเสร็จรอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint_in', 'อู่สีใน'), ('paint_out', 'อู่สีนอก'), ('paint_check', 'รอตรวจสี'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('wash_release', 'ชงล้างรอปล่อย'), ('qc_show', 'รอ QC ตรวจ'), ('sales_check', 'รอเซลล์ตรวจรถขึ้นโชว์'), ('show', 'รถพร้อมขาย (ตรวจรถขึ้นโชว์)'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('transport_check', 'ตรวจขนส่ง'), ('closing', 'รอปิดการขาย'), ('qc_release', 'ตรวจรถรอปล่อย'), ('release', 'ปล่อยรถ (ส่งรูปปล่อยรถ)'), ('sold', 'ขายแล้ว')], default='intake', max_length=20, verbose_name='สเตป'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='stage',
            field=models.CharField(choices=[('intake', 'รับเข้า'), ('photo_wait', 'รถรอถ่ายรูป'), ('repair', 'เช็คซ่อม'), ('repair_done', 'ซ่อมเสร็จรอตรวจ'), ('parts', 'สั่งของ/รออะไหล่'), ('upholstery', 'งานเบาะ'), ('paint_in', 'อู่สีใน'), ('paint_out', 'อู่สีนอก'), ('paint_check', 'รอตรวจสี'), ('film', 'ติดฟิล์ม'), ('wash', 'ชงล้าง'), ('wash_release', 'ชงล้างรอปล่อย'), ('qc_show', 'รอ QC ตรวจ'), ('sales_check', 'รอเซลล์ตรวจรถขึ้นโชว์'), ('show', 'รถพร้อมขาย (ตรวจรถขึ้นโชว์)'), ('reserve', 'จอง'), ('finance', 'จัดไฟแนนซ์'), ('transport_check', 'ตรวจขนส่ง'), ('closing', 'รอปิดการขาย'), ('qc_release', 'ตรวจรถรอปล่อย'), ('release', 'ปล่อยรถ (ส่งรูปปล่อยรถ)'), ('sold', 'ขายแล้ว')], max_length=20, verbose_name='สเตป'),
        ),
    ]
