# Generated by Django 6.0.2 on 2026-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_stage_alter_scanlog_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ราคาขาย (บาท)'),
        ),
    ]
